import { reactive } from 'vue'

export interface ProductRow {
  name: string
  id?: string
  sku: string
  category: string
  status: number | null
  createTime: Date | null
}

export interface CategoryRow {
  id?: string
  value: string
  label: string
  status: number | boolean | null
  children?: CategoryRow[]
  createTime: Date | null
  icon: string
  color: string
}

export interface Pagination {
  page: number // 当前页
  size: number // 每页数量
  total: number // 总数
  tatalPages?: number // 总页数
  limit?: number
}

export const productList = reactive<{ pagination: Pagination; data: ProductRow[] }>({
  pagination: {
    page: 1,
    size: 10,
    total: 50,
  },
  data: [
    {
      id: 'P-1001',
      name: '超薄笔记本 Pro 14"',
      sku: 'LTP-P1001',
      category: 'laptops',
      status: 1,
      createTime: new Date('2024-09-10'),
    },
    {
      id: 'P-1002',
      name: '游戏台式机 酷睿版',
      sku: 'DTP-P1002',
      category: 'desktops',
      status: 1,
      createTime: new Date('2024-08-01'),
    },
    {
      id: 'P-2001',
      name: '旗舰智能手机 X',
      sku: 'PHN-P2001',
      category: 'smartphones',
      status: 1,
      createTime: new Date('2024-07-15'),
    },
    {
      id: 'P-2002',
      name: '入耳式降噪耳机',
      sku: 'AUD-P2002',
      category: 'headphones',
      status: 1,
      createTime: new Date('2024-06-20'),
    },
    {
      id: 'P-3001',
      name: '不粘炒锅 30cm',
      sku: 'KCH-P3001',
      category: 'cookware',
      status: 1,
      createTime: new Date('2024-05-05'),
    },
    {
      id: 'P-4001',
      name: '现代风格三人沙发',
      sku: 'FUR-P4001',
      category: 'furniture',
      status: 0,
      createTime: new Date('2023-12-12'),
    },
    {
      id: 'P-5001',
      name: '男士休闲夹克',
      sku: 'CLT-P5001',
      category: 'mens',
      status: 1,
      createTime: new Date('2024-03-01'),
    },
    {
      id: 'P-6001',
      name: '女士护肤套装',
      sku: 'BTY-P6001',
      category: 'skincare',
      status: 1,
      createTime: new Date('2024-04-18'),
    },
  ],
})

export const categoryList = reactive<{ pagination: Pagination; data: CategoryRow[] }>({
  pagination: {
    page: 1,
    size: 10,
    total: 50,
  },
  data: [
    {
      value: 'electronics',
      label: '电子产品',
      status: 1,
      createTime: new Date('2024-01-10'),
      icon: 'icon-electronics',
      color: '#FF6B6B',
      children: [
        {
          value: 'laptops',
          label: '笔记本电脑',
          status: 1,
          createTime: new Date('2024-02-01'),
          icon: 'icon-laptop',
          color: '#4D96FF',
        },
        {
          value: 'desktops',
          label: '台式机',
          status: 1,
          createTime: new Date('2024-02-05'),
          icon: 'icon-desktop',
          color: '#37C95A',
        },
        {
          value: 'components',
          label: '硬件配件',
          status: 1,
          createTime: new Date('2024-03-12'),
          icon: 'icon-component',
          color: '#F6C85F',
        },
      ],
    },
    {
      value: 'mobile',
      label: '手机与配件',
      status: 1,
      createTime: new Date('2024-01-18'),
      icon: 'icon-mobile',
      color: '#FF8A00',
      children: [
        {
          value: 'smartphones',
          label: '智能手机',
          status: 1,
          createTime: new Date('2024-02-20'),
          icon: 'icon-phone',
          color: '#FF5C93',
        },
        {
          value: 'accessories',
          label: '手机配件',
          status: 1,
          createTime: new Date('2024-03-02'),
          icon: 'icon-accessory',
          color: '#7C4DFF',
        },
      ],
    },
    {
      value: 'audio',
      label: '音频设备',
      status: 1,
      createTime: new Date('2024-01-25'),
      icon: 'icon-audio',
      color: '#00B8A9',
      children: [
        {
          value: 'headphones',
          label: '耳机',
          status: 1,
          createTime: new Date('2024-03-10'),
          icon: 'icon-headphone',
          color: '#3AA1FF',
        },
        {
          value: 'speakers',
          label: '音箱',
          status: 0,
          createTime: new Date('2023-12-05'),
          icon: 'icon-speaker',
          color: '#FFB86B',
        },
        {
          value: 'recorders',
          label: '录音设备',
          status: 1,
          createTime: new Date('2024-04-01'),
          icon: 'icon-recorder',
          color: '#9AD0F5',
        },
      ],
    },
    {
      value: 'home',
      label: '生活用品',
      status: 1,
      createTime: new Date('2024-02-02'),
      icon: 'icon-home',
      color: '#6BCB77',
      children: [
        {
          value: 'kitchen',
          label: '厨房用品',
          status: 1,
          createTime: new Date('2024-02-14'),
          icon: 'icon-kitchen',
          color: '#FF9F1C',
        },
        {
          value: 'cleaning',
          label: '清洁与收纳',
          status: 1,
          createTime: new Date('2024-02-18'),
          icon: 'icon-clean',
          color: '#00C2A8',
        },
      ],
    },
    {
      value: 'furniture',
      label: '家居家具',
      status: 0,
      createTime: new Date('2023-11-30'),
      icon: 'icon-sofa',
      color: '#D17AEE',
      children: [
        {
          value: 'livingroom',
          label: '客厅家具',
          status: 1,
          createTime: new Date('2024-01-05'),
          icon: 'icon-chair',
          color: '#FFC1E3',
        },
        {
          value: 'bedroom',
          label: '卧室家具',
          status: 1,
          createTime: new Date('2024-01-08'),
          icon: 'icon-bed',
          color: '#7DD3FC',
        },
        {
          value: 'office',
          label: '办公家具',
          status: 1,
          createTime: new Date('2024-01-12'),
          icon: 'icon-desk',
          color: '#A0E7E5',
        },
      ],
    },
    {
      value: 'clothing',
      label: '服饰配件',
      status: 1,
      createTime: new Date('2024-03-03'),
      icon: 'icon-clothing',
      color: '#FF6F91',
      children: [
        {
          value: 'mens',
          label: '男装',
          status: 1,
          createTime: new Date('2024-03-10'),
          icon: 'icon-mens',
          color: '#6A5ACD',
        },
        {
          value: 'womens',
          label: '女装',
          status: 1,
          createTime: new Date('2024-03-11'),
          icon: 'icon-womens',
          color: '#FF8DAA',
        },
        {
          value: 'accessories',
          label: '配饰',
          status: 1,
          createTime: new Date('2024-03-12'),
          icon: 'icon-accessory2',
          color: '#FFD166',
        },
        {
          value: 'shoes',
          label: '鞋靴',
          status: 1,
          createTime: new Date('2024-03-13'),
          icon: 'icon-shoes',
          color: '#81FBB8',
        },
      ],
    },
    {
      value: 'beauty',
      label: '美妆与个人护理',
      status: 1,
      createTime: new Date('2024-02-28'),
      icon: 'icon-beauty',
      color: '#FFB4A2',
      children: [],
    },
    {
      value: 'sports',
      label: '运动户外',
      status: 1,
      createTime: new Date('2024-02-20'),
      icon: 'icon-sports',
      color: '#4CC9F0',
      children: [
        {
          value: 'fitness',
          label: '健身器材',
          status: 1,
          createTime: new Date('2024-02-22'),
          icon: 'icon-fitness',
          color: '#90BE6D',
        },
        {
          value: 'outdoor',
          label: '户外装备',
          status: 1,
          createTime: new Date('2024-02-23'),
          icon: 'icon-outdoor',
          color: '#F94144',
        },
        {
          value: 'cycling',
          label: '骑行装备',
          status: 0,
          createTime: new Date('2023-12-16'),
          icon: 'icon-bike',
          color: '#577590',
        },
      ],
    },
    {
      value: 'kids',
      label: '母婴与玩具',
      status: 1,
      createTime: new Date('2024-01-30'),
      icon: 'icon-kids',
      color: '#FFD6A5',
      children: [
        {
          value: 'toys',
          label: '玩具',
          status: 1,
          createTime: new Date('2024-02-02'),
          icon: 'icon-toy',
          color: '#FFB703',
        },
        {
          value: 'baby-care',
          label: '母婴用品',
          status: 1,
          createTime: new Date('2024-02-04'),
          icon: 'icon-baby',
          color: '#9BF6FF',
        },
      ],
    },
    {
      value: 'pets',
      label: '宠物用品',
      status: 1,
      createTime: new Date('2024-03-15'),
      icon: 'icon-pets',
      color: '#BDE0FE',
      children: [
        {
          value: 'food',
          label: '宠物食品',
          status: 1,
          createTime: new Date('2024-03-16'),
          icon: 'icon-food',
          color: '#B8F2E6',
        },
        {
          value: 'accessories-pets',
          label: '宠物配件',
          status: 1,
          createTime: new Date('2024-03-17'),
          icon: 'icon-pet-accessory',
          color: '#C77DFF',
        },
        {
          value: 'toys-pets',
          label: '宠物玩具',
          status: 1,
          createTime: new Date('2024-03-18'),
          icon: 'icon-pet-toy',
          color: '#FFDDD2',
        },
      ],
    },
    {
      value: 'appliances',
      label: '大家电',
      status: 1,
      createTime: new Date('2024-01-14'),
      icon: 'icon-appliance',
      color: '#8EC5FF',
      children: [
        {
          value: 'refrigerators',
          label: '冰箱',
          status: 1,
          createTime: new Date('2024-01-20'),
          icon: 'icon-fridge',
          color: '#B2F7EF',
        },
        {
          value: 'washers',
          label: '洗衣机',
          status: 0,
          createTime: new Date('2023-12-22'),
          icon: 'icon-washer',
          color: '#FFD6E0',
        },
        {
          value: 'aircon',
          label: '空调',
          status: 1,
          createTime: new Date('2024-01-25'),
          icon: 'icon-ac',
          color: '#C1F0FF',
        },
      ],
    },
    {
      value: 'kitchenware',
      label: '厨房器具',
      status: 1,
      createTime: new Date('2024-02-08'),
      icon: 'icon-kitchenware',
      color: '#FFE66D',
      children: [
        {
          value: 'cookware',
          label: '炊具',
          status: 1,
          createTime: new Date('2024-02-09'),
          icon: 'icon-pan',
          color: '#FF7A66',
        },
        {
          value: 'tableware',
          label: '餐具',
          status: 1,
          createTime: new Date('2024-02-10'),
          icon: 'icon-tableware',
          color: '#7BD389',
        },
      ],
    },
    {
      value: 'office',
      label: '办公用品',
      status: 1,
      createTime: new Date('2024-03-05'),
      icon: 'icon-office',
      color: '#B5EAEA',
      children: [
        {
          value: 'stationery',
          label: '文具',
          status: 1,
          createTime: new Date('2024-03-06'),
          icon: 'icon-pen',
          color: '#FFD166',
        },
        {
          value: 'furniture-office',
          label: '办公家具',
          status: 1,
          createTime: new Date('2024-03-07'),
          icon: 'icon-office-furn',
          color: '#8FAADC',
        },
        {
          value: 'storage-office',
          label: '收纳',
          status: 1,
          createTime: new Date('2024-03-08'),
          icon: 'icon-storage',
          color: '#C2F970',
        },
      ],
    },
    {
      value: 'automotive',
      label: '汽车用品',
      status: 0,
      createTime: new Date('2023-10-01'),
      icon: 'icon-car',
      color: '#D4A5A5',
      children: [
        {
          value: 'car-accessories',
          label: '车用配件',
          status: 1,
          createTime: new Date('2023-11-05'),
          icon: 'icon-car-part',
          color: '#F9C2FF',
        },
        {
          value: 'maintenance',
          label: '保养用品',
          status: 1,
          createTime: new Date('2023-11-18'),
          icon: 'icon-tools',
          color: '#A0E7E5',
        },
      ],
    },
    {
      value: 'garden',
      label: '园艺用品',
      status: 1,
      createTime: new Date('2024-03-20'),
      icon: 'icon-garden',
      color: '#9AE6B4',
      children: [
        {
          value: 'plants',
          label: '植物',
          status: 1,
          createTime: new Date('2024-03-21'),
          icon: 'icon-plant',
          color: '#C6F6D5',
        },
        {
          value: 'tools-garden',
          label: '园艺工具',
          status: 1,
          createTime: new Date('2024-03-22'),
          icon: 'icon-garden-tool',
          color: '#FFD7BA',
        },
        {
          value: 'fertilizers',
          label: '肥料',
          status: 1,
          createTime: new Date('2024-03-23'),
          icon: 'icon-fertilizer',
          color: '#FFE4A1',
        },
      ],
    },
    {
      value: 'health',
      label: '保健与护理',
      status: 1,
      createTime: new Date('2024-02-26'),
      icon: 'icon-health',
      color: '#FFDDD2',
      children: [
        {
          value: 'supplements',
          label: '营养保健',
          status: 1,
          createTime: new Date('2024-02-27'),
          icon: 'icon-vitamin',
          color: '#BCE29E',
        },
        {
          value: 'personal-care',
          label: '个人护理',
          status: 1,
          createTime: new Date('2024-02-28'),
          icon: 'icon-personal',
          color: '#A0C4FF',
        },
      ],
    },
    {
      value: 'groceries',
      label: '食品杂货',
      status: 1,
      createTime: new Date('2024-03-02'),
      icon: 'icon-groceries',
      color: '#FFCF99',
      children: [
        {
          value: 'beverages',
          label: '饮料',
          status: 1,
          createTime: new Date('2024-03-03'),
          icon: 'icon-beverage',
          color: '#FFD6A5',
        },
        {
          value: 'snacks',
          label: '零食',
          status: 1,
          createTime: new Date('2024-03-04'),
          icon: 'icon-snack',
          color: '#FFADAD',
        },
        {
          value: 'fresh',
          label: '生鲜',
          status: 1,
          createTime: new Date('2024-03-05'),
          icon: 'icon-fresh',
          color: '#B9FBC0',
        },
      ],
    },
    {
      value: 'tools',
      label: '五金工具',
      status: 1,
      createTime: new Date('2024-01-07'),
      icon: 'icon-tools2',
      color: '#C8DEF6',
      children: [
        {
          value: 'hand-tools',
          label: '手动工具',
          status: 1,
          createTime: new Date('2024-01-10'),
          icon: 'icon-hand-tool',
          color: '#F6B3A7',
        },
        {
          value: 'power-tools',
          label: '电动工具',
          status: 1,
          createTime: new Date('2024-01-11'),
          icon: 'icon-power-tool',
          color: '#9BD3C8',
        },
      ],
    },
    {
      value: 'stationery',
      label: '文具用品',
      status: 1,
      createTime: new Date('2024-03-09'),
      icon: 'icon-stationery',
      color: '#E6E6FA',
      children: [
        {
          value: 'notebooks',
          label: '笔记本',
          status: 1,
          createTime: new Date('2024-03-10'),
          icon: 'icon-notebook',
          color: '#FFF1A8',
        },
        {
          value: 'writing',
          label: '书写工具',
          status: 1,
          createTime: new Date('2024-03-11'),
          icon: 'icon-pen2',
          color: '#CFFAFE',
        },
      ],
    },
    {
      value: 'travel',
      label: '旅行用品',
      status: 1,
      createTime: new Date('2024-02-14'),
      icon: 'icon-travel',
      color: '#FFD3B6',
      children: [
        {
          value: 'luggage',
          label: '行李箱',
          status: 1,
          createTime: new Date('2024-02-15'),
          icon: 'icon-luggage',
          color: '#FFB4A2',
        },
        {
          value: 'travel-accessories',
          label: '旅行配件',
          status: 1,
          createTime: new Date('2024-02-16'),
          icon: 'icon-travel-acc',
          color: '#B2EBF2',
        },
      ],
    },
    {
      value: 'audio-visual',
      label: '视听影像',
      status: 1,
      createTime: new Date('2024-03-25'),
      icon: 'icon-av',
      color: '#C3F584',
      children: [
        {
          value: 'cameras',
          label: '相机',
          status: 1,
          createTime: new Date('2024-03-26'),
          icon: 'icon-camera',
          color: '#FF9AA2',
        },
        {
          value: 'projectors',
          label: '投影仪',
          status: 1,
          createTime: new Date('2024-03-27'),
          icon: 'icon-projector',
          color: '#B5EAEA',
        },
        {
          value: 'recording',
          label: '摄录设备',
          status: 0,
          createTime: new Date('2023-12-30'),
          icon: 'icon-video',
          color: '#D4A5A5',
        },
      ],
    },
  ],
})
